sinonjs/sinon-test

package.json

Also updates the version number to the 2.x versions.

Add sinon as a peer dependency

---

test/test-test.js

Prevents the following from happening...

Fix #8 make sure nextTick is available in test/test-test.js

---

README.md

Removed the notice on needing more maintainers. 
Added a WHY section so that people understand why they should be using this.
Not super sure on the order of the sections ... feel free to suggest modifications.

Remove notice on #12 and add a WHY section

---

.travis.yml
package.json

Added coverage tracking via NYC and coveralls

---

package.json

Ignore updates to rollup

---

package.json

This obviates the greenkeeper PR #64 that for whatever reason breaks the build

Upgrade mocha to latest

---

README.md

The example code could probably be improved. Need a simple example of using `testCase()` to share fakes as per the docs.

Add testCase() docs copied over from the sinon docs @ 1.17.7

---

.gitignore
package.json

Run tests against Sinon 4

---

lib/test.js
test/test-test.js

Fix promises not passed to unit test framework if test function has params

---

package-lock.json
package.json
rollup.config.js

ES6 modules

---

package-lock.json
package.json

Upgrade rollup to lastest

---

README.md
lib/test.js
package-lock.json
package.json

Reintroduce injectIntoThis in local config

---

lib/index.js

Remove configureTest

---

package-lock.json
package.json

Also, bump sinon devDependency to 8.1.0.
Fixes #144

Upgrade sinon peerDependency to allow 8.x

---

package.json

Upgrade sinon peerDependency to allow 9.x

---

.circleci/config.yml
package-lock.json
package.json

Drop node 8 support

---

package-lock.json
package.json

This puts the repository in line with the other @sinonjs/* repositories

Use husky + lint-staged

---

.circleci/config.yml
.eslintrc.yml
.prettierignore
.prettierrc
CODE_OF_CONDUCT.md
README.md
package.json

Use prettier@2

---

package-lock.json
package.json

Hello! Peer dependencies are not matching again, so I bumped sinon version here.
This PR is just the same as #180 and #185 but for sinon 12.

feat: add support for sinon 12

---

package.json

This PR adds support for `sinon@13`

Add support for Sinon 13

---

.eslintrc.yml
.github/stale.yml
.github/workflows/main.yml
README.md
lib/test.js
lib/utils.js
package-lock.json
package.json
rollup.config.js
test-repos/esm-bundle-pre.mjs
test-repos/esm-pre.mjs
test/helpers.js
test/test-test.js

Upgrades required to release new version after fixing #194.

Required upgrades
